### PR TITLE
.has() method and newValueCallback

### PR DESCRIPTION
**Pull request by vanderlee**
I needed to have a Dictionary that is able to create a new value if a new key is accessed.
This change implements an optional newValueCallback argument.
If not specified, observableDictionary works as usual.
If specified with a callback, observableDictionary will call the callback with the key as it's first  argument. The return value of the callback will be used as the value for the new key.
You need this if the Knockout template is dynamically determined by the viewmodel itself.

In order to be able to check for existance of keys without using .get(), I also added a .has() method.

### CODE REVIEW

**Comment by jamesfoster** [comment]
I don't see the point to this. You could just as easily load the dictionary with your expected values when the source changes. It doesn't make sense to change the dictionary when you read from it.

The `has` method is a nice idea tho.

**Comment by vanderlee** [comment]
I admit it's use is not quite obvious and most project probably won't need to use it.

The project that inspired this change was one where I had basically a user-editable tree of HTML templates with editable content (which is where the dictionary comes in to play). The choice of HTML template was user-editable too so upto the moment the template was rendered, the code had no idea which dictionary items were required.

Practical options using current dictionary were to require maintaining a list of dictionary items used in a each template or add a new data-bind property to be run during rendering, with all dictionary fields specified in the data-bind syntax.

Both of these solutions required to maintain the dictionary items twice, both required a bunch of distributed code to deal with making sure the dictionary was loaded before the individual items were loaded.

The alternive I ended up using, the newValueCallback, didn't require any additional administration of the dictionary items, just a simple callback for each dictionary which constructed an "empty" object for the new key.

If you don't think this is useful enough for inclusion, then no problem and I'll just set up my own github project for it. I'd rather it be integrated with Dictionary though, for obvious code quality reasons.

**Comment by vanderlee** [comment]
p.s. Your current version in git seems to have some stuff at the very start of the file that neither NetBeans not GitHub seems able to handle. Perhaps a (partial) BOM left-over? Either way, it's most likely what's causing the entire file to appear changed.

**Comment by vanderlee** [comment]
Can I take the lack of further response as a reply that this won't be included?

**Comment by agrath** [comment]
I just needed some very similar functionality, I was dynamically building my keys as part of a nested foreach and needed to store state for each item within the nested foreach (think: crosstab or similar UI)
pre-render, i'd have to figure out programmatically what each of the potential keys were and populate them with my default value.
In my case, I was binding to &lt;input type="checkbox" data-bind="checked: dictionary.get("dynamically_constructed_string_key_using_context") "/&gt;
As I checked inputs for the first time, the keys were created with the value true, and then I unchecked them, and they changed to false, however without a UI interaction, the keys were never created in the actual dictionary. 
This meant that selectAll/selectNone/selectInvert functionality had nothing to iterate over.
Hope this makes sense.
I have raised my own pull request with a small tweak that handles just the "default value" aspect. #7

**Pull request closed without merging**
